{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smartpg-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    {{- toYaml .Values.sealedSecrets.encryptedData | nindent 4 }}
  template:
    metadata:
      name: smartpg-secrets
      namespace: {{ .Values.namespace | default .Release.Namespace }}
    type: Opaque
{{- end }}
