{{- if not .Values.sealedSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: smartpg-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | default "mongodb://admin:password@mongodb-service:27017/?authSource=admin" | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | default "secretkey" | quote }}
  MONGO_USERNAME: {{ .Values.secrets.mongoUsername | default "admin" | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.mongoPassword | default "password" | quote }}
{{- end }}
