namespace: smartpg-dev

frontend:
  image:
    tag: "5315481"

tenantService:
  image:
    tag: v1.0.0

paymentService:
  image:
    tag: v1.0.0

messService:
  image:
    tag: v1.0.0

complaintService:
  image:
    tag: v1.0.0

notificationService:
  image:
    tag: v1.0.0

mongodb:
  persistence:
    createStorageClass: true

sealedSecrets:
  enabled: true
  encryptedData:
    JWT_SECRET: AgB8tg43cUIVH+LGd6wIXlEhaAAqYbycwYYTnGIEYue7IeRNhCFGYRaqbYnopEJN8PVcEkNjzoQilVOhoT+voULbNRHYaCSe17nzOAumM4M3NRSIWYMjblr1G6oqnChBqYrJscFRNdEHhtCE32QImRVQ4Icpssofe9XKqsz4q7NhwYQqa3N/cXcQH/qUs0fV2GNueoawKybgpT/859TMevk3hMAGDjmp0CJkYBH4uFqoPU0rbvZNL5yAkVrhoKOMrDkkn6n6R3ZM5l1lG0t7MTDkIqxcplQfxcxSYfmccw1hIY+h7Zv0DeqYOeXH6WPR9tYhdmQqscOqukK/qH7M6i0YACBD05cam2bZ7Z8U+B4edT2viNMLPz+u/icNbVBU9BYw4GzkeqhztO+WQcxVlV8ekR5M2dp/uJfpf700fHsv5P+C5crgjzC7K5DGkjUJy3ASssca5GPaPFSIA9esDZWDGEM2R6trPPP2Owk75WL3jPZUIgtp5bB90Q94YXQcr7YIKwrjOdopWb9cR6LF1FXENKdejXzkZrBG3cHAf1o83Vm8YZHJgd7CLkvhQco+Vwd48S9XFgF/fTy3NN/LmEFYrKA13p5gB1QyeIs0fwReLqBoU/K5OHhUQc8/MecU5SYL3aYs8CFpSbNZX8EhReoE/DQLYO6GuGCr4LUk5+xVyXFZflVWMvIg5nlI8LqCIeGxBCzzpDD2jTA=
    MONGO_PASSWORD: AgA69MVmVLopTZ7+XRg97v+A7kDqLPbn1Tm5YTzmHg6L/bf1VV/zHkfNNl4oVSBQD4kzv7+zDMc+ENQLNGqetMDt3rbEDG3GxDMICLuY0qhq8ACZrCv1XMA2HAzVArt8/wa02TtuN42WQ2R1SJawyLJ5lhdSVEi4dstFjvNHCwFDT4UCTl1IOv63oNwBk14rVAkxcpb5/xvPffS/30X2XZ/p7n1FX02KlpDXjge+l+F5uZjt3sgD17+grYdAeL789oBoM8vh//z05odePKNxJHQPSc6M18/68r7cqxNwsnwtGQRKVRlxRyYL7bJA1mWHJDqQznFPRqtvIGyYX4lTMzwPyjrMSj5JWzd4iSTzWM5K51kTpxznGYgryasfH4ngCApsrm0e0YlQnNID68DOIbunwOi6PfcQ2c6rx7no/7+biblzVuQ5Kqf49kISKlcx951d98a3NvMb4wJB+IS3Up6KKWzKFHpRoxLwOGv1e9VMMpsningX3uixVSHKddti27jzt6wuz0WjaKgEUJkScGEAR//mQszjhHK1TA8xPmThtqZ9hmLCY7vDEXHrpe9rU5DbyG3UrfpEj72gw6B5N/4qFsX5fmvsQQpq2Wn3VO3qdo5TLD39b2J+UcTVcWmK6kgEMHIL5bEMbdTtEfwqJ8FZmvwwgO06HRSFWot0ryiz6MX5g9hu1/O9q1WsHxVifF2mG5dBATuT+Q==
    MONGO_URI: AgCqenPxs9HKYrQVlWAhJEqOp+B9w81bq3HiBUGrxQmIHMPtMvLqFA0js8phA7ln9omdiXxc+8mO1UDZRXVHbQB0eSicY+Rf3mjxDMNuAtKVQMbNsF4EVB+/5V9TOokk12P7YDwuiztkGjF89z9BMZMW4ECaQ9G+0wDUlPmuOraRRksUXH+rFV6vwLpioftpVVKCcn5j438IceCaQBrnDb7yP6qav3DhjujVG/xwWR0n3mHYa28/v+LgTvg5/ftgyDYsCRYB/HkLM2KkqAtf/apWvfMu5cAYBGqcWBTOIjEPQfMGmEbLIRv4r4f3yZjyVaYyl+u+gR6EGJFh9q4eBREG6ekaMwpa7YEu/ozK4aI5nn94TRfhXQkRuWXBr6d0SsCmp2JkbJVvVmczEUdxQ5Jf+w2JKmkFeb4+KrC+kLEbsEjgLHHSWok1eDdx6vaJJbD9WJH7VgEaY8O+osFoQ8+mWdvIOXloXm3CrPGz+bxi4fF2qLxZp6UM2ZmdOUxK+bEw9B8Jq18e8mTrpzbHJpYIt/JhY5T+C8cIOnFThHfATaTgUZYQy3cXiMxYL3paHdgbZpm54FKVPP3BAM5ZkYyS/nj7mHpED7PGi8UvrBrr0RoQoeHSh+cndt9usyzMcPmYql4qzPo+YGs9foPN+tqTF3NQa44oeuIqyMAUUruFqX5jo7ZzOvk+4gXK0EUdRoPE6JwUiuKZ9YFmKNVbmE1P1V5Y6LDWPZcRzfeEBs4XxkiLdwDcO1sbhb3A3TeXySnkrWnHf5RPZFQ/Jz0pO48=
    MONGO_USERNAME: AgCSqneGVCfuxcf/i/dvOYoEQ8ZYKEJnOOBc75zD1hwyjKxtxN62f3bT+lgGHTsqYJbl+JCBvX8J9wpF5ATInVRNTG81JR4LwCq1zxdJ7VK4JRUI9aYrYbXMm1rcpVTN1qJXcPrwTmBePJ4b22HuK82IFwMEBi1TFpc00en6druFFPAafEFtrr8YXCCoVnDSwhZboJG2FqWH0y9om2pDq85k8VsVm09xu4wrFG6U5XOYx7hoWlhi1jvQ3W7jBandYm/OUxtkHTTVEaoBucH8P29oC6Othzz6pPN8wxSe3co02/E/3dS7kMjrT+SyJuy4hMpIwgLme/UQVR5EpQSc82DaHcQgR4JewEgoFwANgDz6xRa5xH7tsaLozi9K3rU4BWdc/koNzAlOLFIchTEpcCzoAKihpEl4yHwskynLBUu642y+eFHrqNC++jgfWRh+gUqEZgCeqiiPj9e1T2tnrFMnfZ21ItCYVinI7XRycDAySMl70W+qVVTE2oZfu3Su49N7b4YgCkCWQ8h+ObXQ5iap+4MBcT6kQJpzgcayxCahtVzj/SqwkBXCVr2ZB5v5Ed6ZmYPIna9UeS3gLgpZNw3TFCQOZrZGYHtQEgUIoRUt4nRCzYF07A9eb+Z++ToQ24USWvF7hhCr9fEKfRMjkSXBk2LoV4+wNEOcZyNAQ5aPr+WZBddQciQ9hVDipCXixzDm5FHPzA==
