namespace: smartpg-prod

frontend:
  image:
    tag: v1.0.0

tenantService:
  image:
    tag: v1.0.0

paymentService:
  image:
    tag: v1.0.0

messService:
  image:
    tag: v1.0.0

complaintService:
  image:
    tag: v1.0.0

notificationService:
  image:
    tag: v1.0.0

sealedSecrets:
  enabled: true
  encryptedData:
    JWT_SECRET: AgAvhD+Za3npuQD82nAjPZT1jMDKkNcsgeC3dvyPSzbPpV3GlVoiajNyYDkb2/toojqF68sTo9kg3xVo58BXIaUSFsVYjSp6piF7mCiwyYBIgMZaCQ/xa0wYjso1OnkgN+aUaneeaj/o76zG0Vkg+vkY5NzWI42GRyUndzYx+mAb8Rq47CD3J/U2h5th8ENImJcMfVDQY73i6A8PXgetIbSo/QIae1uVOXQ/VKuqiYvqMg1aXeIc8lIM+2R2oJjhJufOvWnn5tTrIcETFz9lJIUnsEFr53tutABNMbi0e/gt92RmzPHKJLoRnO3JS0w0NDtx+Ce0lAxH/BDuho3NdUZXBurFrp1PZvyfTZW1VN5ipb1uOaj7ozl5v+69S2wRxNx6IFNGp2ZKqKdHu+IncOdsbYKTnvrQA7A5b5kNCiKcHbczlE+tLe2zgD3PAn2gvPPCU7KTSV3soM45X1oVkmHpNxYVnRKkiOE8Qm+IGtBP35CVwn6n0SvpiTSWJSU+Wz2T+JHJrHx5CyBk/81WfwDTQhf12uAcuSniM2M12wMFOKmDMYI0Vq6U+bmA92JScPLdcq80Q+rl8GK8zNNpxtm6FP0lk/IIaqzfMqc0GdQPbxHm8cl8cloZ+0ZhnN7AxzdC9ozCAXYZi0/VXzH+4Kgjz/nON16tOm6Y3jf1bGWu0agOhngFQY50HqCxu/Pbl/pSsoKkvup1xiI=
    MONGO_PASSWORD: AgCc6hKVGgAOFp6cSnFnBxnM8VwMizZSz/TUBIjCemV9b0PUHLpmwpV/kK6pOHtzgQUQ/7w9Kbb1mZXL+7hEJ4qMuEWAwSQD4Jw9tnVBK4hXleg9/xWMNemwsOd5RzeUDrC+akFujSs9Ec1qRCWw4oBNs8TnLSOAEZkkKt4Pl9snUVg4u97z9Y0ulFXPkN6lqoSl0PKXJ/s21XZhufpcZHcXagOLwyd+gBN8r6zveJ0HZXFjRFri1JiOojgdOZCyQYKGky4wiagje894HsgZCFLnnT8mElbl2R4bJcQUEA++e45MpS7cHtogU3xq+4hiynBUXcxJ+dCUboYc+KUHbrEERWbemNd1Don1hN91pJfXtLBEbwpg+o/rw3KV6NY5C1En3ADK4HdwRyh5CXaG+inVtDrgHN8X3NwCVhTDCiCjheN7nMx7zWvRrD8GGEV/9khZeVdmuNah7tcrX+zq75tOt7NapJ5thF5cMhkCDW1tzI/Bt2xuJq0a3r4hrEfQp8LnfM6IAkkm0yjs0lxYw+wLQoBLPeHv580+ydExppQ6/9apJhZmeZaws0RF58l5j4GEJ46DChX7MuzsQtd2uqK5hFLCmw2V75W3a+1sp+y/dOxoeQWNrx20L9OgQjFey+xxm0BhBZ/tDvuIigMS9dkW8u4/nTkqab+2VGYRzx4FhynW2ognUklANg8h9EUK/io2pJV2t6zvrQ==
    MONGO_URI: AgCpCM6yKQ+TFDSN/Sbqk5VBB+qiXgmjkNVwV/JWzV8bqNecet5VBA+InjMsHPjoc05AXJ81nQb5ed/zi407UMcfBXYOwRa5irmLowZb6cSNpB6wfckFPEbQ1tjrpR9lCHxN9CxKrDebdtbPnAACoxHG0EmprejvXpLxuSdtwFuqIoUaSulpbA3Qj15WRgv5vBLXEO4qFYCfip+KY68T3NjzY6zt1EERcLzaaeqDCwDe06M4pX9tBavZZ4VOMEkhv5H2MFf/ZMsaF6d6AupiZUyJ12Hhz7ymY/4HuCyjWysjSj6j/IUQf1ciYHkEAJgol63TwfYEqrQjtoWIsxs1ZrP7iG0BoelN1XVfNsmOiLUPnOF7vSBpWSJVCHRjG3F1wn/Z3e6bDn44ZppCPKXZSRx0Sb0t13suy8rtgkMt2+AzdLKqqQUlNCpCcWQwm14SJg9+UkDoEUfRlfEKsFVXJiGDjVPUCYWrwZRc6KKIzFxUlwXEQObTT90vlrzpz5cQYCEmLurgzkj8BVtZCkxXSTAKvvDuC6IXg5QYsJrRU1XxCi/fJejP8sZyTUITIFbR9AonOdE5csUIvNQK5FPCMTGtEIvjFR57ZZF1Jd8D7krXVD3P5q0XktRK7dQ9bquEpf83rXe3unE0Jfi0cX7Ic3g1UgQlVbdy03CXbKAATRzazOHjI+SvC6Am1ImtaJysVflFBTRbRkbln2iMOi3PwSTWgG55mxW8iz9IvwKvGH2t5wcSJSxDW5ycC+btUuDfXjm/qjmSRTAZ4AHHqlDbyU5w
    MONGO_USERNAME: AgBwXxtgcKrvBM/J+AzcAbTvI+6yCK2DHwU+O7r2zerMDLd0vNZ+oQRSq80CkexAIswf5wOu4TTqbLwkm/Ohk/AsoBHbZtwr4E/Zxcy0tndcXTq8BjzAMBHQLGqv8Mevsi2xaS1QJ/zFqrtMZQEZHosMwBe7RgFnxL2MtuI2gdXATmtiBbiBNP4PI0xi524RLXLXyslhm1fJp/0ZgkzG4ov9WuIOBziGNbpAoy2MDTuTFXMY3f/JeIOEst2QXthbrg88d5YPjD1o6BhsRbbWVhJFPxNuAN3/Cl3KaSEUdqHxjUo4IJ0/B9mJKM7j83cVc17UrQDnWqdMpgalR7PADIUCdy1dPc/EGnJv5Exkz+KuysEcqzCBnxk2qapqoC74d9p+o9Ktu0fmmsWgyM4LOod8vphNu1S5iyVqKZSbIKNVx6qMbdHJo1XD6WPEdSaEUU3vT1hNTv0CEdLKx4IhPQvHf4twmTJaGJQAlClyoXwBwMEKg7ZgjIidappKsc6E1z39ocj4fXrasVB0XW9flXCLfAbVZyuzrhAu/wxquB4ROBLdpZrPHTSvtFB++98F7QL4uYZz7TKsYLrBSJAS5nfdSuRMq6jvB6fWxJ7vENJcncRSAKp8u18HYyupo7uEwsfpUwndbb7RU3uoRT4fPpWjQcCPSiquWfkTB3Q9CnOUdrOhM1gnsKyZgkE+5tqejcetxCP4sA==
