namespace: smartpg-prod

frontend:
  image:
    tag: v1.0.0

tenantService:
  image:
    tag: v1.0.0

paymentService:
  image:
    tag: v1.0.0

messService:
  image:
    tag: v1.0.0

complaintService:
  image:
    tag: v1.0.0

notificationService:
  image:
    tag: v1.0.0

mongodb:
  persistence:
    createStorageClass: false

sealedSecrets:
  enabled: true
  encryptedData:
    JWT_SECRET: AgA0qDDiuxb0Zk8dQ6XGclIa+VEXbvTXqb/rOFH8L2i0nnaoROHdC5eKPPwirZKYls7fzGOVI8uOcPPCwwRDfQ/BJOsg/xkQ/kjYJ8ShSmuWGp54G9ONy60jWal1GpACX4N25tr1DRzWe78RpQG2UPDcNknZmGP1Iak8OPaoTV7jnt0NjuZoOayiRpT36AA2KltmlHPJ2MX5r5pvJ50h3Y6ZulZqUEQIk3upnJsSE3/WEcgpCs1JGlNIkicPRKM/tW73zhTJ2tDoJH/JParl7T1ep2fgB6x2T1Mzig9MryLLQE5EVdSJjvioCq2xTvlFt/nB6uDvZD6/LBtF/OqG/YFY34Ky4as0wvH6HW/XdAZKGkFxY5T7eWA2lTw+d3Bnf25Ns39n8+qMOfAc7JI+rGfhCIA/90JNpd/Z7UXkY3WVjgUQnoJpvnERNLzhquNtL+GXGtksPjIqZHWm9RwVtbMphtFVW31B9c393+wA3vSAJzqeKZTK/IHZDXinI95kYBhvfKOw9NRGt3gblCrUDUz/nM15TGxTS4qd7cIe5sq6yRqqh9Me+Bi5RlmXj1oGHgRYreFWtZoJ8CnmILciYvwPLtFTlVOTslX/fHeCpEkPKI2r5ml0dXTT/GHo/UX0tYfiFijyeJBYyrNJM4iEJalhav4RnQ8rLbHn8m/RFEkb5dPxxt04KId1oZn5wSZ2y7Vhx0RkzDjTlZY=
    MONGO_PASSWORD: AgCUipFNyqHE8nVy9+QUAyBQXJ6p3wir+pP3tgPn/6uVGj/CqOsMVEG0ltirnoymMzVUXAhIycNwAHx8j84GnyEBFNGn+MG6DSjZfh5sKZul8MTzi6rYedL8uegYFQiQBqT2+WOAcFFQMdTW9FvAvLyAwt0gBamS3ejw8zro5xsj3SRlyitNCXKZR40lu9MMtgtznsy+TQZS9Cb7bh0YKjn9sXqvtlXbLsg7nUOi+42PkuaEsI4WgXKmp9ZExpVrEvg/MfhrxEgBK23+yPHdFHtJ2/2bJ1eocO37UaJB3+cXiBO9cYJfCbEbmLai4u+ms30BaxIFUKr880mvrlYz8BevRFG93R3okXTxKlCvjK3JLQEA7PHmtrowF5Gq5toU8hI0NQcT3tUHSFN/gUZ0ZIEH20CppAp98SK9iuxbl+mttTgLb4ZZu8gH8pK/S0/LHAh4xtKVfwqgpogH/yqoDutP0XoH+UuWn3px9nZyAEp6+qgctzo2K9zCoa1ZUgQFzcW1H0E5VT5NoatAl+CAdEct1h0ZRkI+LBQbOP8Iuos9ugAD2MfvqxQziSZDAl+smpYeqUoFo8IpSULpuj9RJqBEMOdVuumJ2h1o1CrBPUxXD0xvtSYyx9i/EZnXNW5ljSwO/x47I37p+KJXMjDmFiqxN05HFha3TwNa+ehaGjmZMI+WkwWg3jLjEOYXBInrFAMaMfPwXNz0sQ==
    MONGO_URI: AgAcYS1KUEdqRbfgWZ/2QnAqGExF+VbOhsr9lLu7xS9tWFaQ3v8u7uuj8xTRCwQwPCn+qLEF2V3WgvuUwC7w8gcDLw46uZZymb5ujDdIkLq/Wqyc7t1bc7PkB1U/qv+BIirPcli7sc3AYGM6qAs+JyV52Xtt8lVRdGNgy4LpcmzGuzGKG0Y0ADmBcameueG0BTQZwaiHbBFjRwymqadvq3DB8a6K31nTKvX49pDMp9/iENT0NoUHQwH3VXIKN1CnGvheb8dbae0kxFMhjEbZ4HK04EHYCTx0tXXKvw8q4WhHOjeXth8BMD8I7ex236W/CZ2cgty/L6lBeBezSWjXy8NrfdptsIhINtKtJsz2kWLZYEPrrnTvyXpQ4MSHOLjQEo0TVtFUc7dL9HQDFrHcojhHQBv5ubJ5nFz8OK4ZCGTQTJ30/YDxD+kvGoI/PpLHDtZKU43jcmssFUAXFLOjeuPNh/oCNPROo+DySjcG9+h4/VNaQHKeRiWNNcsO/1R+OKn1LWhhPky3U3sfXPM0ANDdvgcZcu206ymQGZGEBnCUnGmYC+9n5Zkvm4zdVWxzyk1vRoKYQjKnAQ4pGgbpdxrdSJY1cy/WNTQ7XdfoTUv30/tRcuWLAxcmGC2Syf8sGA2QULAP1wQb5YTqhX9xHJBkYWW5nBZdYJmu1U7ZRawTSlR/6hJ28HtRAeXXSsnFqLZHvvdwr5h0P26MjFIX9qG7C8hWeUTIYhdJPi8ZNGF26GHhkiphxqvdiWFE6/LigvuHZwmSnkuzN2UivU+nioA=
    MONGO_USERNAME: AgBNGVTbnvIU0cNplqFHMaL2c/ZguSro6zrRC/P4aSliXgbdSbm0tSswLGfF36uTCT3zi8l8shTN3NyQ+dWZOe+XbSNGYobIx/JiyFPXTr9XCGzSWHxfquRJg5S2s7fvaq9/lds+se4wYCl8Wj1GIcKUhnsSR/3ewz7ls4GBVsUV9l1V02JU/vRDjkd3IZq+pBD5huVppaUc0CcU/Q5m/3EYkdjS0lR5oCdIVe1D3MjDxvl+CaPzcc42rxwsD49tj2nJoB/SfAdl9lhWeXO0YRQOdZwdh1cyTJZIdePMp1x7NEYSmZ0s1SB19nYlaXsu3cNaZcxg3L3HVYMwS6rzeIv+eD9IWrSPvYnVcpgKTrVvJmo/TWc94OyXw/4EepPyGlAuB+C6GFCeg0oU1zukDJ5n8CrtdZeoReGwZbAIxX3Eaq+VkR1cI1mSE25Bx8tQsjj7NeJcOUGv4WDOiSvhAUC5u9iCdFB0DYWw6VRIEhqgey+OYwEYFg8BuFIWcFERyuWfc9WNDZQp/NpsRoao0A4aXlNYNR1tnWCxXV/iY3bmFZPdk1rXxZ2/m2DOf+U9g99LkyLMYOuT4YPv0qxKdVoUxikkM+TPBEAT0a6Q9/M4lSAW1o0vjaWQMmiWXT8gwSrk9VJB0/KUdSciVRN6Xd4kRcvB9WUkhLJUIdPGt38DYvXNdYr5e0SLlm2WZ7yRbNNp0EHF3A==
