namespace: smartpg-dev

frontend:
  image:
    tag: v1.0.0

tenantService:
  image:
    tag: v1.0.0

paymentService:
  image:
    tag: v1.0.0

messService:
  image:
    tag: v1.0.0

complaintService:
  image:
    tag: v1.0.0

notificationService:
  image:
    tag: v1.0.0

sealedSecrets:
  enabled: true
  encryptedData:
    JWT_SECRET: AgBhhaVOFdJoh77SUGpQNSlReegp0fCewXIeQSOhstrx2DQPiOw9zaPVpJEy0SsEvk8OSLEY94G58hOiMbHFwJDH/f2JgQ4atQ7K0dxbmD4nCapS/4uTumCZWi15bH7CsilJKs8lA1wRU/a8dIno5U0vG/iJX5it3VcQdbkNx++0vNzo9csBDT8NIBPIIO8WCZPirQeeFFg55MVsv5wDwZ+LWxyjlBwR7hfcT6ImWR22VlZ8KdDtIuRoXzS9Ig+N5ebSnaNVB7LYxR6uxtqRE0zbRCOxjCIzYMVBGgfKxa4i405CCkfrHjJAYd+gjnl7IORw7/y/Ua/yUur7mhGfzsJ3u5uRAHMddSZiruqFhB/HzHv6+8SSB7au9KX9p9GdJCgb3GJI27T/Jl65wq/z++yB2DO6V18FEvAoqg9IEOkw6ngpJXnyXc7tVyLiYtGsddHoQJc8u2ARFrGJOXzQQi3Zly/fHKLuYcmQx0KFdTfTGEkUwH8JXd0fxSbCCqLsC7LsSu01BWNwKd0oi47IemVEW5f98jQ6aDX/yA1LM2RkyHMPoAmAyLuo03M12/DLiUdgZMiIRNvicr/PRImC9ySkKrxksSBombkQHn707ZfNJHlaatkbygqr5orjzUAVkETqgZOoWcClviffQ08IEVa8sq6Z0o7fl1v4kgHKMNTkIFLX/fzZN0lmh6wLTg0HigpVFJM5XJIEbHs=
    MONGO_PASSWORD: AgBxiiBUxQHfLO8kBHWzNToP+m0Kp6X3cx/Xvh6TPqInt5JXyn6LQJI1uWGXCSnMQCPz/nDlQrpF8ztnSd7wP8HePXpDzr0W3fLfLSXY6A2gn3oi9aBYTcFdOH979TUavBGMswnaIzuxzdayQWKzPdIuN7TPhTMmXhDPlt4issAPyXYUveL/2PPXwCiTOldILI9YEUKl9DRPqQnEwHnqjmmDW9opOQ0a40inX5sn2Kn69/oUqqdcQatIlKhsq27CWCpSWUAoI4DGvK/Gd2lSDkxKIHIsGr7ycjcqyelStd0WufGLdtE/JfrnYhDg36IecKiuwfHEFfAxvGUPvm3chQC22/JFZCRSz0/zvlL/BtOqtfBZBf9eTpeoNw7oW/PFVnh8/4vAuV+QXB/YEx+VgKBMtddV79ufHxN016QaaI//ABVC8rvWAROjU7pBApV3ANblrhvj1uFe2DhjTIAFsM6ESJGv8BnlfxpiiLIc1+JCUT55y6dSlQNPZKwuZIN5ow1slibxrbVJQZPU88lTeX6plALuTbE8ENp/cI0/VwXLbQ8KwQB1f+YmVveR+IxqkuWJGa9pew6RC5lSiVfqm7AupEf6YNdRLBsa96yd3Xag5YGO3PtosvFHeInMIs2ACTAAttq5ZD35ps1zxtIhP17rZsXWztjUAbpaKlGgtdx3nI1ZxEyUE9FGYJYYo62JBMVuRA7uqh2QIg==
    MONGO_URI: AgBnW21i1pRqFwv8WtwIvs6wjX2TMPKB6YHVxd/D6wnVPfQGO3n7W9tBzBnl25Z5KlD9b+9UKZxSVrOou57LK2BKKaRJD4JwIjXmF3Etshd6zT5SYysEuTphj1iuq7IUK1wW3s9OTHNTpPsw/YBByv6p0xr5m8rmCyj0rs3gLAYqDK59/5F7vI0AGIfewT82cuuZyVAodyPSPrWRHHy3L4+BLuCzK3d6cEC9y/VJB+6NYBt4X2KNMmPgrsLxtkizlXDSNNQukHusVUTzO+z4O5/mP8cKRsV1MyVWl1Af/pi3/OxkMFCPUqwep3brOw2YudIlZZNp3KnqINHwQwPz+6pl6BuGibCMopiQWZNzab8qgtSsZempyE33i5/p7+aOJi2AAVQ690WaKtP16fp00dNpBGaVn+5bZ/LK95Yy0I2Hf/PG9Ke/yrMmdxPqRTGg8sAcl6lw2pRf5keGhLtZiMXkjdB9RcQ2nEYvDUX2GuJyIzYLz6xmF7ru4EmlzGGdhHY2SRnE1Hbele6nNp+1ONgaeFCMYweNBzXmb1nODK13IjUe2mpKMvLRyR2mCOyQEYX2iPrGHG8YlGlNFYvSchqcha/M/GRJB6PoeyfTYBO59eM3bxf4+YqHnSlLYB5QFnUPZA5vaejqFuEzPP2lF7AtwmEp+MO3aXJ87XkB7i+QhSkVa0KJesYd+JF9lpeEJuFxmnuwiFInmA+ZtkAGEwxp/SG/iAH9gnYmEKAjp7cVQOG7nE0OB7TN6phpHj2px/UTPAXEcfzFpTpojGPb4roy
    MONGO_USERNAME: AgAWSTd85tZxNqFHe6rwMHeBrP6cT+H9hni5MSROA/zxU5NP6AQU3iNkXawVO167N5R3xohZGeg/leW6FI6lsHZWjw7tONkbNsyix0q09lf3+epuqW5h3b+sEVRYc1DXe9VwUj3eTCSZcVQc/q0U2oZduxIVqsqaAKWCKJ8EKwzQIraStyJmrEMqfebXED1ZNWsSTl/utIrAuzhhUnfOeqW5uq1Tuk4Mutx0X2k7cF26Be10XGx44KTzYyQZQdlep8lj2pUbnNHenmrNltAmf2aS+HV9/5BPeWvv8b0gtdcgzCVp3oZFWUrj0BxEcyAJ4GfMDqjYnUbzKX7lLhE9vfaDAxZ4eAnHQylLi1Iu/xspst9b9Ne+OT3TeHg8AeXnKnAQnlYI6Pj2kWbRkh1fL+w/mhkbLWzdfi2osgmZgGaLguGB8QVRQOOhnTuH3Y9AcSkS6sL9rp4l8CiTeVUB4gDAxEHpqO1xpIV/gLgh4kjBcOwOdJIYk5lMkVEJrLDQuh4ktRUn4l7FqzZTMdnz6HGV8BkqdNjBIEpEf1oe0M2reqjNR3QBYgDQ3KXUhMHnMOEpFokaJqjuOvnMBTve5pYSy2SQdrSnkxhIRP8org5BAn5LZt/C/0xZPyYW5YMBDsc6yRFsOp5gAwskw0QzGPjSWxjZuhgerO8DY00+ur7p6Jh81Gwrf3DcX6r/K7R1qzLFrfo25w==
