apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smartpg-prod
  namespace: argocd
  labels:
    environment: prod
    app: smartpg
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/SmartPG-Application/SmartPG-helm.git
    targetRevision: main
    path: helm/smartpg
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: smartpg-prod

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /spec/rules
    - group: storage.k8s.io
      kind: StorageClass
      jsonPointers:
        - /metadata/annotations
        - /metadata/resourceVersion
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
